# Render deployment configuration for Arabic Visa Management System

services:
  # Backend Service
  - type: web
    name: fursatkum-backend
    env: node
    plan: free
    buildCommand: cd server && npm ci --omit=dev
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://andydaddy080:1s8trWSbR9J8rNkq@cluster0.g5rsvmu.mongodb.net/visa_system?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: 1f8bdb5f7d73b5a423069d428e4bf95fc391b320e7eec411b5d534dcf54b0097
      - key: CORS_ORIGIN
        value: https://fursatkum-frontend.onrender.com
      - key: FRONTEND_URL
        value: https://fursatkum-frontend.onrender.com
    healthCheckPath: /api/health

  # Frontend Service
  - type: web
    name: fursatkum-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://fursatkum-backend.onrender.com
      - key: REACT_APP_ENV
        value: production

# MongoDB Atlas is used instead of Render's database service
# Atlas connection string is configured in backend environment variables
